fix: Mark deprecated configuration options
KaotoIO/uniforms-patternfly pull request #78
Opened 2024-03-05 22:56 UTC by shivamG640

2024-03-06 08:08 UTC, lordrip reviewed
Looks good, good work.

2024-03-06 08:08 UTC, lordrip commented on src/wrapField.tsx
> +  );
In this case, we're creating a new `labelIcons` variable on every render, which is not ideal, because it forces additional renders because of this.

2024-03-06 08:08 UTC, lordrip commented on src/wrapField.tsx
> +  );
The alternative is to write this, directly in the `labelIcon` property of the `<FormGroup />` component or leave it as it was before but try to combine the deprecated popover with the hint popover.

2024-03-06 08:08 UTC, lordrip commented on src/BoolField.tsx
> +      {(props.field as any).deprecated && <FieldDeprecatedPopover />}
Could you try creating a single component that receives `default`, `description`, and `deprecated` values at once so we can provide a single component here, the same for the `wrapField` function? Maybe that will help with the margin topic.

2024-03-06 14:25 UTC, shivamG640 commented
This is how it looks now!
![image](https://github.com/KaotoIO/uniforms-patternfly/assets/73224329/d0563a24-4aa6-49a6-baa2-0891b5f83e34)
![image](https://github.com/KaotoIO/uniforms-patternfly/assets/73224329/f93e0b94-e5a2-4b21-9e62-97b8f2266943)

2024-03-06 14:31 UTC, lordrip requested changes
@shivamG640 visually, it looks great, we just need to preserve the original component and provide a new one that encapsulates both the `Hint` and the `Deprecation` one. This is because this library is a fork, hence we need to be as file-compatible as possible.

2024-03-07 15:37 UTC, lordrip commented on src/FieldDetailsPopover.tsx
> + */
[minor] This title seems misplaced :thinking: , is this the right title?

2024-03-07 15:37 UTC, lordrip approved these changes

2024-03-07 15:37 UTC, lordrip commented on src/FieldDetailsPopover.tsx
> + */
We can take a look in an upcoming PR

2024-03-07 15:37 UTC, merged